steps:
  # Build the Docker image, injecting the secret as a build arg
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build \
          --build-arg NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=$$MAPS_API_KEY \
          -t gcr.io/$PROJECT_ID/YOUR_APP_NAME .
    secretEnv: ['MAPS_API_KEY']

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ddev']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'run'
      - 'deploy'
      - 'ddev'
      - '--image=gcr.io/$PROJECT_ID/ddev'
      - '--region=europe-west1'
      - '--platform=managed'
      - '--allow-unauthenticated'

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_GOOGLE_MAPS_API_KEY/versions/latest
      env: 'MAPS_API_KEY'